apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: apply-crossplane-credentials
  namespace: openshift-pipelines
spec:
  params:
    - name: cluster-name
      type: string
    - name: pipeline-image
      type: string
  workspaces:
    - name: source
  steps:
    - name: apply
      image: $(params.pipeline-image)
      imagePullPolicy: Always
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        fleet-apply-crossplane-creds \
          --cluster-name "$(params.cluster-name)" \
          --source-dir "$(workspaces.source.path)/clusters/$(params.cluster-name)"
