---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-pull-secret
spec:
  params:
    - name: cluster-name
      type: string
    - name: pipeline-image
      type: string
    - name: source-namespace
      type: string
      default: openshift-config
    - name: source-secret-name
      type: string
      default: pull-secret
  steps:
    - name: create-pull-secret
      image: $(params.pipeline-image)
      imagePullPolicy: IfNotPresent
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        fleet-create-pull-secret \
          --cluster-name "$(params.cluster-name)" \
          --source-namespace "$(params.source-namespace)" \
          --source-secret-name "$(params.source-secret-name)"
