apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-cluster-namespace
  namespace: openshift-pipelines
spec:
  params:
    - name: cluster-name
      type: string
    - name: pipeline-image
      type: string
  steps:
    - name: create-namespace
      image: $(params.pipeline-image)
      imagePullPolicy: Always
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        fleet-create-namespace --cluster-name "$(params.cluster-name)"
