apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - create-cluster-namespace.yaml
  - apply-crossplane-credentials.yaml
  - wait-for-aws-credentials.yaml
  - transform-aws-credentials.yaml
  - validate-cluster-inputs.yaml
  - apply-cluster-crs.yaml
  - wait-for-hive-ready.yaml
  - wait-for-managed-cluster.yaml
  - extract-spoke-kubeconfig.yaml
  - label-for-post-provision.yaml
  - delete-cluster-resources.yaml
  - wait-hive-uninstall.yaml
  - cleanup-hub-artifacts.yaml
  - verify-deprovision.yaml
