apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: transform-aws-credentials
spec:
  params:
    - name: cluster-name
      type: string
    - name: pipeline-image
      type: string
  steps:
    - name: transform
      image: $(params.pipeline-image)
      imagePullPolicy: IfNotPresent
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        fleet-transform-aws-creds \
          --cluster-name "$(params.cluster-name)"
