---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: verify-deprovision
  namespace: openshift-pipelines
spec:
  params:
    - name: cluster-name
      type: string
    - name: pipeline-image
      type: string
  steps:
    - name: verify
      image: $(params.pipeline-image)
      imagePullPolicy: IfNotPresent
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        fleet-verify-deprovision --cluster-name "$(params.cluster-name)"
