- op: replace
  path: /metadata/name
  value: f6f3eba2-redisvirt
- op: replace
  path: /metadata/namespace
  value: f6f3eba2-redisvirt
- op: replace
  path: /spec/clusterName
  value: f6f3eba2-redisvirt
- op: replace
  path: /spec/platform/aws/region
  value: us-east-2
- op: replace
  path: /spec/provisioning/installConfigSecretRef/name
  value: f6f3eba2-redisvirt-install-config
- op: replace
  path: /spec/provisioning/sshPrivateKeySecretRef/name
  value: f6f3eba2-redisvirt-ssh-key
