- op: replace
  path: /metadata/name
  value: f6f3eba2-redisvirt
- op: replace
  path: /metadata/namespace
  value: f6f3eba2-redisvirt
- op: replace
  path: /spec/clusterName
  value: f6f3eba2-redisvirt
- op: replace
  path: /spec/clusterNamespace
  value: f6f3eba2-redisvirt
