[tox]
envlist = test, yamllint, black, mypy, pylint, bandit
skipsdist = false

[testenv:test]
commands = pytest -v --cov fleet --cov-report term-missing --cov-fail-under 100

[testenv:yamllint]
commands = yamllint -c .yamllint .

[testenv:tekton-lint]
allowlist_externals = npx
commands = npx tekton-lint tekton/

[testenv:validate-kustomize]
commands = pytest tests/validation/

[testenv:black]
commands = black --check fleet/ tests/

[testenv:mypy]
commands = mypy fleet/

[testenv:pylint]
commands = pylint fleet/

[testenv:bandit]
commands = bandit -r fleet/
