[tox]
envlist = test, yamllint, black, mypy, pylint, bandit
skipsdist = false

[testenv:test]
deps =
    pytest
    pytest-cov
commands = pytest -v --cov fleet --cov-report term-missing --cov-fail-under 100 --ignore=tests/validation

[testenv:yamllint]
deps = yamllint
commands = yamllint -c .yamllint .

[testenv:tekton-lint]
allowlist_externals = npx
commands = npx tekton-lint 'tekton/tasks/*.yaml' 'tekton/pipelines/*.yaml' 'tekton/triggers/*.yaml'

[testenv:validate-kustomize]
deps =
    pytest
commands = pytest tests/validation/

[testenv:black]
deps = black
commands = black --check fleet/ tests/

[testenv:mypy]
deps =
    mypy
    types-requests
commands = mypy fleet/

[testenv:pylint]
deps = pylint
commands = pylint fleet/

[testenv:bandit]
deps = bandit
commands = bandit -c pyproject.toml -r fleet/
