apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../cluster-templates/aws-ha/base/crossplane

patches:
  - target:
      kind: User
      name: cluster-placeholder-ocp-installer
    path: patches/user.yaml
  - target:
      kind: Policy
      name: cluster-placeholder-openshift4installerpolicy
    path: patches/policy.yaml
  - target:
      kind: UserPolicyAttachment
      name: cluster-placeholder-policy-attachment
    path: patches/policy-attachment.yaml
  - target:
      kind: AccessKey
      name: cluster-placeholder-access-key
    path: patches/access-key.yaml
