apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - eventlistener.yaml
  - triggerbinding-provision.yaml
  - triggertemplate-provision.yaml
  - triggerbinding-deprovision.yaml
  - triggertemplate-deprovision.yaml
