apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: provision-binding
  namespace: openshift-pipelines
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.after)
    - name: cluster-name
      value: $(extensions.cluster_name)
