apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pre-provision-template
spec:
  params:
    - name: git-repo-url
    - name: git-revision
    - name: cluster-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: pre-provision-$(tt.params.cluster-name)-
      spec:
        pipelineRef:
          name: pre-provision
        params:
          - name: cluster-name
            value: $(tt.params.cluster-name)
          - name: git-repo-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
        taskRunTemplate:
          serviceAccountName: fleet-pipeline
          podTemplate:
            securityContext:
              fsGroup: 0
            imagePullSecrets:
              - name: fleet-pipeline-pull-secret
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: gp3-csi
