apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: deprovision-template
  namespace: openshift-pipelines
spec:
  params:
    - name: cluster-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: deprovision-$(tt.params.cluster-name)-
        namespace: openshift-pipelines
      spec:
        pipelineRef:
          name: deprovision
        params:
          - name: cluster-name
            value: $(tt.params.cluster-name)
        serviceAccountName: fleet-pipeline
