---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: post-provision-binding
spec:
  params:
    - name: cluster-name
      value: $(body.cluster_name)
    - name: tier
      value: $(body.tier)
    - name: dns-zones
      value: $(body.dns_zones)
    - name: base-domain
      value: $(body.base_domain)
    - name: keycloak-issuer-url
      value: $(body.keycloak_issuer_url)
