- op: replace
  path: /metadata/name
  value: 379b5094-ibmvirt
- op: replace
  path: /metadata/namespace
  value: 379b5094-ibmvirt
- op: replace
  path: /spec/clusterName
  value: 379b5094-ibmvirt
- op: replace
  path: /spec/platform/aws/region
  value: us-east-2
- op: replace
  path: /spec/provisioning/installConfigSecretRef/name
  value: 379b5094-ibmvirt-install-config
- op: replace
  path: /spec/provisioning/sshPrivateKeySecretRef/name
  value: 379b5094-ibmvirt-ssh-key
