apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crossplane/iam-user.yaml
  - crossplane/iam-policy.yaml
  - crossplane/iam-attachment.yaml
  - crossplane/iam-access-key.yaml
  - install-config-secret.yaml
  - clusterdeployment.yaml
  - machinepool-worker.yaml
  - managedcluster.yaml
