- op: replace
  path: /metadata/name
  value: test-cluster-01
- op: replace
  path: /metadata/namespace
  value: test-cluster-01
- op: replace
  path: /spec/clusterName
  value: test-cluster-01
- op: replace
  path: /spec/clusterNamespace
  value: test-cluster-01
