apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 379b5094-ibmvirt

resources:
  - ../../../cluster-templates/aws-ha/base/hive

patches:
  - path: patches/install-config.yaml
  - target:
      kind: Namespace
      name: cluster-placeholder
    patch: |
      - op: replace
        path: /metadata/name
        value: 379b5094-ibmvirt
  - target:
      kind: ClusterDeployment
      name: cluster-placeholder
    patch: |
      - op: replace
        path: /metadata/name
        value: 379b5094-ibmvirt
      - op: replace
        path: /metadata/namespace
        value: 379b5094-ibmvirt
      - op: replace
        path: /spec/clusterName
        value: 379b5094-ibmvirt
      - op: replace
        path: /spec/platform/aws/region
        value: us-east-2
      - op: replace
        path: /spec/provisioning/installConfigSecretRef/name
        value: 379b5094-ibmvirt-install-config
      - op: replace
        path: /spec/provisioning/sshPrivateKeySecretRef/name
        value: 379b5094-ibmvirt-ssh-key
  - target:
      kind: MachinePool
      name: cluster-placeholder-worker
    patch: |
      - op: replace
        path: /metadata/name
        value: 379b5094-ibmvirt-worker
      - op: replace
        path: /metadata/namespace
        value: 379b5094-ibmvirt
      - op: replace
        path: /spec/clusterDeploymentRef/name
        value: 379b5094-ibmvirt
  - target:
      kind: ManagedCluster
      name: cluster-placeholder
    patch: |
      - op: replace
        path: /metadata/name
        value: 379b5094-ibmvirt
      - op: add
        path: /metadata/labels/tier
        value: base
      - op: add
        path: /metadata/labels/environment
        value: development
  - target:
      kind: KlusterletAddonConfig
      name: cluster-placeholder
    patch: |
      - op: replace
        path: /metadata/name
        value: 379b5094-ibmvirt
      - op: replace
        path: /metadata/namespace
        value: 379b5094-ibmvirt
      - op: replace
        path: /spec/clusterName
        value: 379b5094-ibmvirt
      - op: replace
        path: /spec/clusterNamespace
        value: 379b5094-ibmvirt
  - target:
      kind: Secret
      name: cluster-placeholder-install-config
    patch: |
      - op: replace
        path: /metadata/name
        value: 379b5094-ibmvirt-install-config
      - op: replace
        path: /metadata/namespace
        value: 379b5094-ibmvirt
