apiVersion: v1
kind: Namespace
metadata:
  name: openshift-pipelines
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: multicluster-engine
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management